---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/locked: "true"
    flux.weave.works/locked_user: Richard Scholz <7677934+nextstepman@users.noreply.github.com>
  name: catalogue-db
  namespace: other-shop
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogue
  namespace: sock-shop
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: catalogue
      containers:
      - image: weaveworksdemos/catalogue:0.3.5
        name: catalogue
