apiVersion: v1
kind: Service
metadata:
  labels:
    application: catalogue-db
  name: catalogue-db
  namespace: other-shop  
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    application: catalogue-db
