---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: catalogue
  name: catalogue
  namespace: sock-shop
  annotations:
    flux.weave.works/automated: "false"
spec:    
  template:
    spec:
      containers:
      - name: catalogue
        env:
        - name: "ENVIRONMENT"
          value: "dev"    